# Generated by Django 4.2 on 2023-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=30, verbose_name='Root')),
                ('part_of_speech', models.CharField(choices=[('Verb', 'Verb'), ('Adverb', 'Adverb'), ('Adjective', 'Adjective'), ('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Participle', 'Participle'), ('Preposition', 'Preposition'), ('Numeral', 'Numeral'), ('Particle', 'Particle'), ('Conjunction', 'Conjunction')], max_length=15, verbose_name='Part of Speech')),
            ],
        ),
    ]
