# Generated by Django 4.2 on 2023-04-14 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_area', '0003_word_dictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddictionary',
            name='user',
        ),
        migrations.AddField(
            model_name='worddictionary',
            name='user',
            field=models.ManyToManyField(related_name='word_dictionary', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
