# Generated by Django 4.2 on 2023-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0006_worddictionary_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=100, verbose_name='Word'),
            preserve_default=False,
        ),
    ]
