# Generated by Django 4.2 on 2023-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0007_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedword',
            name='russian_value',
            field=models.CharField(default='', max_length=100, verbose_name='Russian Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='russian_value',
            field=models.CharField(default='', max_length=100, verbose_name='Russian Value'),
            preserve_default=False,
        ),
    ]
