# Generated by Django 4.2 on 2023-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_read_articles',
            field=models.IntegerField(default=0, verbose_name='Amount of Read Articles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='amount_read_word',
            field=models.BigIntegerField(default=0, verbose_name='Amount of Read Words'),
        ),
    ]
