# Generated by Django 4.2 on 2023-04-14 16:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_amount_read_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to=authentication.models.get_user_avatar_image_path, verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
