# Generated by Django 4.2 on 2023-04-14 18:25

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True, validators=[authentication.models.validate_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=100, null=True, validators=[authentication.models.validate_name], verbose_name='Second Name'),
        ),
    ]
