# Generated by Django 4.2 on 2023-04-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_first_name_alter_profile_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='amount_read_word',
            new_name='amount_read_words',
        ),
    ]
